# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "TheAppBusinessTeam" do
  pod 'hpple', '~> 0.2.0'
end

target "TheAppBusinessTeamTests", :exclusive => true do
  pod 'Kiwi'
end

